### PR TITLE
Setup publishing, dokka & knit

### PR DESCRIPTION
**Pull request by nomisRev**
This PR cleans up the project a bit more, and sets up Dokka, Knit and configuration to publish to Sonatype/Maven Central 🥳

It also moves the `demo` to documentation so it can be published on the Dokka website.

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
Great work @nomisRev! :partying_face: We'll need better examples and documentation but we're making great progress! When we finalize the 0.0.1 API, I'll try to spend some time adding KDoc + more/better examples.

**Comment by nomisRev** [comment]
Perfect, I'll create the proposal PR for the `refine` DSL after this PR as we discussed in #8 👍 Then we'll be ready for an a first 0.0.1 release 🥳 

Whoever gives the second approval feel free to merge ☺️

**Review by ustits — APPROVED** [review]
🚀

**Comment by ustits** [comment]
@nomisRev btw, maybe it will be helpful, played a little bit with your proposal about refine DSL in krefty, definitely like it

https://github.com/ustits/krefty/blob/main/krefty-arrow/src/commonMain/kotlin/dev/ustits/krefty/arrow/Refinement.kt
https://github.com/ustits/krefty/blob/main/krefty-arrow/src/commonTest/kotlin/dev/ustits/krefty/arrow/RefinementTest.kt

**Comment by nomisRev** [comment]
@ustits nice 😍 If you're interested feel free to open a PR, then we can collaborate there as well. Otherwise I'll open one later this week.

**Pull request merged**
